### ISSUE TITLE
  self.load_path = 'PeopleDaily-9718'，这个文件夹是什么内容

### ISSUE THREAD

**Issue by hhlcode** [learnway299/ERNIE-BiLSTM-CRF-Pytorch-Chinese_NER#2]

**Comment by learnway299** [comment]
人民日报原始数据

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年8月2日 21:23
收件人: ***@***.***>
抄送: ***@***.***>
主题: [learnway299/ERNIE-BiLSTM-CRF-Pytorch-Chinese_NER] self.load_path = 'PeopleDaily-9718'，这个文件夹是什么内容 (Issue #2)


―

**Comment by kkk39** [comment]
data里面不是有People_daliy的数据集么，result里面还要放嘛

**Comment by learnway299** [comment]
Data是数据源 result是NER处理结果

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年10月10日 19:26
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [learnway299/ERNIE-BiLSTM-CRF-Pytorch-Chinese_NER] self.load_path = 'PeopleDaily-9718'，这个文件夹是什么内容 (Issue #2)


data里面不是有People_daliy的数据集么，result里面还要放嘛

―

**Comment by vectorsket** [comment]
您好为什么我报错：Traceback (most recent call last):
  File "main.py", line 139, in <module>
    fire.Fire()
  File "/root/anaconda3/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/anaconda3/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/anaconda3/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "main.py", line 46, in train
    model = load_model(model, name=config.load_path)
  File "/content/drive/MyDrive/ERNIE-BiLSTM-CRF/utils.py", line 120, in load_model
    model.load_state_dict(torch.load(name, map_location=lambda storage, loc: storage))
  File "/root/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'result/MASA-98386'应该怎么解决
