### ISSUE TITLE
报错：FileNotFoundError: [Errno 2] No such file or directory: 'result/MASA-98386'应该怎么解决

### ISSUE THREAD

**Issue by vectorsket** [learnway299/ERNIE-BiLSTM-CRF-Pytorch-Chinese_NER#3]
您好为什么我报错：Traceback (most recent call last):
File "main.py", line 139, in
fire.Fire()
File "/root/anaconda3/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
component_trace = _Fire(component, args, parsed_flag_args, context, name)
File "/root/anaconda3/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
component, remaining_args = _CallAndUpdateTrace(
File "/root/anaconda3/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
component = fn(*varargs, **kwargs)
File "main.py", line 46, in train
model = load_model(model, name=config.load_path)
File "/content/drive/MyDrive/ERNIE-BiLSTM-CRF/utils.py", line 120, in load_model
model.load_state_dict(torch.load(name, map_location=lambda storage, loc: storage))
File "/root/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
with _open_file_like(f, 'rb') as opened_file:
File "/root/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
return _open_file(name_or_buffer, mode)
File "/root/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 211, in init
super(_open_file, self).init(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'result/MASA-98386'应该怎么解决

**Comment by onlinin** [comment]
请问您解决了吗？可以交流一下吗
